version: '3'

services:
 forntend-server:
  container_name: fronted
  build: ./client
  image: nginx-client-server
  ports:
   - 8080:80
  networks:
   - esnet
  depends_on:
   - backend-server

 backend-server:
  container_name: backend
  build: ./server
  image: py-es-server
  environment:
   - ES_HOST=db
   - ES_PORT=9200
  networks:
   - esnet

networks:
 esnet:
  driver: bridge
